from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

from rtl_bug_agent.schema import RtlChunk


SV_KEYWORDS = {
    "always", "always_comb", "always_ff", "always_latch", "and", "assign", "automatic",
    "begin", "bit", "case", "casex", "casez", "default", "else", "end", "endcase",
    "endfunction", "endmodule", "endpackage", "endtask", "enum", "for", "function",
    "generate", "genvar", "if", "import", "inout", "input", "int", "integer", "localparam",
    "logic", "module", "negedge", "or", "output", "package", "parameter", "posedge",
    "return", "signed", "struct", "task", "typedef", "unique", "unsigned", "wire",
}


def chunk_sv_files(
    rtl_dir: str | Path,
    client: "OpenAICompatibleClient | None" = None,
) -> list[RtlChunk]:
    """Chunk all .sv files in *rtl_dir*.

    If *client* is given, each file is pre-screened by an LLM that
    classifies sections as BEHAVIORAL / STRUCTURAL.  Purely repetitive
    structural sections (register instances, generated wire lists) are
    skipped during chunking.
    """
    from rtl_bug_agent.rtl.prefilter import classify_sections

    paths = sorted(
        list(Path(rtl_dir).glob("*.sv")) + list(Path(rtl_dir).glob("*.v"))
    )
    chunks: list[RtlChunk] = []
    skipped = 0
    total = len(paths)

    for idx, path in enumerate(paths):
        if _should_skip(path):
            skipped += 1
            continue

        # LLM pre-filter for structural sections
        skip_ranges: list[tuple[int, int]] = []
        if client:
            try:
                skip_ranges = classify_sections(path, client)
            except Exception:
                pass  # fall back to full chunking

        chunks.extend(chunk_sv_file(path, skip_ranges=skip_ranges))

        if skip_ranges:
            total_lines = sum(e - s + 1 for s, e in skip_ranges)
            print(
                f"  [{idx + 1}/{total}] {path.name}: "
                f"skipped {len(skip_ranges)} structural section(s) "
                f"({total_lines} lines)"
            )

    if skipped:
        print(f"  Skipped {skipped} auto-generated file(s) (reggen/topgen/...)")
    return chunks


def chunk_sv_files_structural_aware(
    rtl_dir: str | Path,
    client: "OpenAICompatibleClient | None" = None,
) -> tuple[list[RtlChunk], list[dict[str, object]], list[dict[str, object]]]:
    """Chunk RTL files and split out structural-only chunks.

    Returns:
        behavior_chunks: chunks that should still go through Phase 1 spec generation
        manifest: lightweight classification records for all chunks
        structure_facts: compact static facts extracted from structural chunks
    """
    chunks = chunk_sv_files(rtl_dir, client=client)
    annotated_behavior: list[RtlChunk] = []
    manifest: list[dict[str, object]] = []
    facts: list[dict[str, object]] = []

    for chunk in chunks:
        split_chunks = (
            _split_continuous_region_for_structure(chunk)
            if chunk.kind == "continuous_region"
            else [chunk]
        )
        for piece in split_chunks:
            info = _classify_structural_mode(piece)
            annotated = RtlChunk(
                chunk_id=piece.chunk_id,
                kind=piece.kind,
                source_file=piece.source_file,
                module=piece.module,
                line_start=piece.line_start,
                line_end=piece.line_end,
                title=piece.title,
                context_summary=piece.context_summary,
                code=piece.code,
                dependencies=piece.dependencies,
                semantic_class=info["semantic_class"],
                guard_context=info["guard_context"],
                structure_refs=info["structure_refs"],
                compile_time_context=info["compile_time_context"],
            )
            manifest.append(
                {
                    "chunk_id": annotated.chunk_id,
                    "source_file": annotated.source_file,
                    "line_start": annotated.line_start,
                    "line_end": annotated.line_end,
                    "kind": annotated.kind,
                    "semantic_class": annotated.semantic_class,
                    "guard_context": annotated.guard_context,
                    "structure_refs": annotated.structure_refs,
                    "compile_time_context": annotated.compile_time_context,
                    "reason": info["reason"],
                }
            )
            facts.extend(_extract_structure_facts_from_chunk(annotated))
            if annotated.semantic_class != "structure":
                annotated_behavior.append(annotated)

    return annotated_behavior, manifest, facts


def _should_skip(path: Path) -> bool:
    """Return True if *path* is an auto-generated file (reggen, topgen, etc.).

    Scans the first 10 lines for ``auto-generated by`` markers.  These
    files are structural glue (register wiring, top-level connections)
    and almost never contain behavioural bugs.
    """
    try:
        header = "".join(
            path.read_text(encoding="utf-8").splitlines()[:10]
        )
    except (OSError, UnicodeDecodeError):
        return False
    return "auto-generated by" in header.lower()


def chunk_sv_file(
    path: str | Path,
    skip_ranges: list[tuple[int, int]] | None = None,
) -> list[RtlChunk]:
    src_path = Path(path)
    lines = src_path.read_text(encoding="utf-8").splitlines()
    scopes = _scope_by_line(lines)

    # Add pre-filter structural skip ranges as "structural_skip" spans
    protected: list[tuple[int, int, str, str]] = []
    for start, end in (skip_ranges or []):
        protected.append((start, end, "structural_skip", f"struct_{start}_{end}"))

    i = 1
    while i <= len(lines):
        clean = _strip_line_comment(lines[i - 1])
        if _starts_function_or_task(clean):
            end = _find_until(lines, i, (r"^\s*endfunction\b", r"^\s*endtask\b"))
            protected.append((i, end, "function_task", _block_label(clean, i)))
            i = end + 1
            continue
        if _starts_always(clean):
            end = _find_begin_end_block(lines, i)
            kind = _always_kind(clean)
            protected.append((i, end, kind, _block_label(clean, i)))
            i = end + 1
            continue
        if _starts_generate_for(clean):
            end = _find_begin_end_block(lines, i)
            protected.append((i, end, "generate_for", _block_label(clean, i)))
            i = end + 1
            continue
        i += 1

    all_spans: list[tuple[int, int, str, str]] = protected[:]
    all_spans.sort(key=lambda item: item[0])

    other_spans = _find_uncovered_spans(lines, all_spans, max_lines=140)
    all_spans.extend(other_spans)
    all_spans.sort(key=lambda item: item[0])

    counters: Counter[str] = Counter()
    chunks: list[RtlChunk] = []
    for start, end, kind, label in all_spans:
        if not _has_meaningful_code(lines[start - 1:end]):
            continue
        module = _dominant_scope(scopes, start, end)
        safe_scope = _safe_id(module or src_path.stem)
        safe_kind = _safe_id(kind)
        safe_label = _safe_id(label)[:56] or f"line_{start}"
        base = f"{safe_scope}__{safe_kind}__{safe_label}"
        counters[base] += 1
        chunk_id = f"{base}__{counters[base]:03d}"
        code = "\n".join(lines[start - 1:end])
        chunks.append(
            RtlChunk(
                chunk_id=chunk_id,
                kind=kind,
                source_file=str(src_path),
                module=module,
                line_start=start,
                line_end=end,
                title=_title(kind, label, module, start, end),
                context_summary=_context_summary(kind, module, start, end),
                code=code,
                dependencies=_extract_identifiers(code),
            )
        )

    # Post-processing: merge adjacent continuous_region chunks that were
    # artificially split (e.g. by the max_lines cap) but belong to the same
    # semantic region.  Only merges chunks of the same kind with no semantic
    # boundary (always / function / generate) between them.
    chunks = _merge_adjacent_same_kind_chunks(chunks, gap_threshold=2)
    return chunks


def _scope_by_line(lines: list[str]) -> dict[int, str | None]:
    scope: str | None = None
    result: dict[int, str | None] = {}
    for idx, raw in enumerate(lines, start=1):
        clean = _strip_line_comment(raw)
        module_match = re.match(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)\b", clean)
        package_match = re.match(r"^\s*package\s+([A-Za-z_][A-Za-z0-9_$]*)\b", clean)
        if module_match:
            scope = module_match.group(1)
        elif package_match:
            scope = package_match.group(1)
        result[idx] = scope
        if re.match(r"^\s*endmodule\b", clean) or re.match(r"^\s*endpackage\b", clean):
            scope = None
    return result


def _strip_line_comment(line: str) -> str:
    return re.sub(r"//.*$", "", line)


def _starts_always(line: str) -> bool:
    return bool(re.match(r"^\s*always(?:_(?:comb|ff|latch))?\b", line))


def _starts_function_or_task(line: str) -> bool:
    return bool(re.match(r"^\s*(?:function|task)\b", line))


def _starts_generate_for(line: str) -> bool:
    return bool(re.match(r"^\s*for\s*\(\s*genvar\b", line))


def _always_kind(line: str) -> str:
    match = re.match(r"^\s*(always(?:_(?:comb|ff|latch))?)\b", line)
    return match.group(1) if match else "always"


def _block_label(line: str, start: int) -> str:
    named = re.search(r"\bbegin\s*:\s*([A-Za-z_][A-Za-z0-9_$]*)", line)
    if named:
        return named.group(1)
    func = re.search(r"\b(?:function|task)\b.*?\b([A-Za-z_][A-Za-z0-9_$]*)\s*(?:\(|;)", line)
    if func:
        return func.group(1)
    return f"line_{start}"


def _find_until(lines: list[str], start: int, end_patterns: tuple[str, ...]) -> int:
    for idx in range(start, len(lines) + 1):
        clean = _strip_line_comment(lines[idx - 1])
        if any(re.match(pattern, clean) for pattern in end_patterns):
            return idx
    return len(lines)


def _find_begin_end_block(lines: list[str], start: int) -> int:
    depth = 0
    seen_begin = False
    for idx in range(start, len(lines) + 1):
        clean = _strip_line_comment(lines[idx - 1])
        begins = len(re.findall(r"\bbegin\b", clean))
        ends = len(re.findall(r"\bend\b", clean))
        depth += begins
        if begins:
            seen_begin = True
        depth -= ends
        if seen_begin and depth <= 0:
            return idx
        # Verilog "always" blocks without begin/end: extend until
        # we hit a bare keyword at the start of a line (new block,
        # assign, instance, etc.)
        if not seen_begin:
            if _is_continuation(clean):
                continue
            # Don't end on the first line's semicolon — Verilog always
            # blocks without begin/end may span multiple lines
            if idx > start and ";" in clean:
                return idx
    return len(lines)


def _is_continuation(line: str) -> bool:
    """Return True if *line* looks like it continues the current block."""
    stripped = line.strip()
    if not stripped:
        return True  # blank lines continue
    if stripped.startswith(("//", "`")):
        return True
    # Continuation keywords
    if re.match(r"^(if|else|else\s+if|case|for|while|endcase|end\b)",
                stripped):
        return True
    # Line starts with a signal name or register assignment (indented)
    if re.match(r"^[a-zA-Z_]", stripped) and not re.match(
        r"^(module|endmodule|always|assign|wire|reg|input|output|inout|"
        r"parameter|localparam|function|task|generate|endgenerate)",
        stripped,
    ):
        return True
    return False


def _find_uncovered_spans(
    lines: list[str], covered_spans: list[tuple[int, int, str, str]], max_lines: int
) -> list[tuple[int, int, str, str]]:
    spans: list[tuple[int, int, str, str]] = []
    start: int | None = None
    last_meaningful: int | None = None

    def flush(end: int) -> None:
        nonlocal start, last_meaningful
        if start is not None and last_meaningful is not None:
            label = _other_label(lines[start - 1:last_meaningful])
            spans.append((start, last_meaningful, "continuous_region", label))
        start = None
        last_meaningful = None

    for idx in range(1, len(lines) + 1):
        if _covered(idx, covered_spans):
            flush(idx - 1)
            continue
        raw = lines[idx - 1]
        meaningful = bool(_strip_line_comment(raw).strip()) and not _strip_line_comment(raw).strip().startswith("`ASSERT")
        if not meaningful:
            if start is not None and last_meaningful is not None and idx - last_meaningful > 14:
                flush(idx - 1)
            continue
        if start is None:
            start = idx
        last_meaningful = idx
        if idx - start + 1 >= max_lines:
            flush(idx)
    flush(len(lines))
    return spans


def _other_label(lines: list[str]) -> str:
    joined = "\n".join(lines[:20])
    for pattern in (
        r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)",
        r"^\s*package\s+([A-Za-z_][A-Za-z0-9_$]*)",
        r"^\s*typedef\s+.*?\b([A-Za-z_][A-Za-z0-9_$]*)\s*;",
        r"^\s*localparam\s+.*?\b([A-Za-z_][A-Za-z0-9_$]*)\b",
        r"^\s*([A-Za-z_][A-Za-z0-9_$]*)\s+u_([A-Za-z_][A-Za-z0-9_$]*)\b",
    ):
        match = re.search(pattern, joined, flags=re.MULTILINE)
        if match:
            return "_".join(part for part in match.groups() if part)
    return "declarations_or_instances"


def _covered(line_no: int, spans: list[tuple[int, int, str, str]]) -> bool:
    return any(start <= line_no <= end for start, end, _, _ in spans)


def _dominant_scope(scopes: dict[int, str | None], start: int, end: int) -> str | None:
    names = [scopes.get(line_no) for line_no in range(start, end + 1) if scopes.get(line_no)]
    if not names:
        return None
    return Counter(names).most_common(1)[0][0]


def _has_meaningful_code(lines: list[str]) -> bool:
    for raw in lines:
        clean = _strip_line_comment(raw).strip()
        if clean and not clean.startswith("`ASSERT"):
            return True
    return False


def _extract_identifiers(code: str, limit: int = 40) -> list[str]:
    code_without_comments = "\n".join(_strip_line_comment(line) for line in code.splitlines())
    identifiers = re.findall(r"\b[A-Za-z_][A-Za-z0-9_$]*\b", code_without_comments)
    counts: Counter[str] = Counter(
        ident for ident in identifiers if ident not in SV_KEYWORDS and not ident.startswith("ASSERT")
    )
    return [ident for ident, _ in counts.most_common(limit)]


def _safe_id(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value or "chunk"


def _title(kind: str, label: str, module: str | None, start: int, end: int) -> str:
    scope = module or "file"
    return f"{scope}: {kind} {label} ({start}-{end})"


def _context_summary(kind: str, module: str | None, start: int, end: int) -> str:
    scope = module or "file scope"
    if kind.startswith("always"):
        return f"{scope} 中的 {kind} 过程块，行 {start}-{end}。"
    if kind == "continuous_region":
        return f"{scope} 中的连续非过程逻辑区域，包含声明、实例化或直接组合赋值，行 {start}-{end}。"
    if kind == "function_task":
        return f"{scope} 中的函数或 task 定义，行 {start}-{end}。"
    return f"{scope} 中的声明、实例化或寄存器描述上下文，行 {start}-{end}。"


def _merge_adjacent_same_kind_chunks(
    chunks: list[RtlChunk], gap_threshold: int = 2
) -> list[RtlChunk]:
    """Merge adjacent same-kind chunks that were artificially split (e.g. by
    the max_lines cap in _find_uncovered_spans), but that belong to a single
    semantic region with no always/function/generate boundary between them.

    Only ``continuous_region`` chunks are candidates for merging, because they
    represent the "everything else" that the chunker didn't classify as a
    named procedural block.  A gap of up to *gap_threshold* lines (inclusive)
    is tolerated — this handles trivial whitespace or single-line separators
    that don't constitute a real semantic boundary.
    """
    if len(chunks) <= 1:
        return chunks

    # Sort by source_file, then line_start
    sorted_chunks = sorted(chunks, key=lambda c: (c.source_file, c.line_start))

    merged: list[RtlChunk] = []
    run: list[RtlChunk] = []

    for chunk in sorted_chunks:
        if not run:
            run.append(chunk)
            continue

        last = run[-1]
        same_file = chunk.source_file == last.source_file
        same_kind = chunk.kind == last.kind
        mergeable_kind = chunk.kind == "continuous_region"
        adjacent = (chunk.line_start - last.line_end) <= gap_threshold

        if same_file and same_kind and mergeable_kind and adjacent:
            run.append(chunk)
        else:
            merged.append(_collapse_run(run))
            run = [chunk]

    if run:
        merged.append(_collapse_run(run))

    # Restore original file ordering (first appearance)
    file_order: dict[str, int] = {}
    for idx, c in enumerate(chunks):
        file_order.setdefault(c.source_file, idx)
    merged.sort(key=lambda c: (file_order.get(c.source_file, 0), c.line_start))
    return merged


def _classify_structural_mode(chunk: RtlChunk) -> dict[str, object]:
    code = chunk.code
    lower = code.lower()
    compile_time_context = _extract_compile_time_context(code)
    guard_context = [{"kind": "compile_time", "text": item} for item in compile_time_context]
    structure_refs: list[str] = []

    if chunk.kind == "continuous_region":
        line_roles = [_line_role(line) for line in code.splitlines()]
        has_structure_lines = any(role == "structure" for role in line_roles)
        has_behavior_lines = any(role == "behavior" for role in line_roles)
        if has_structure_lines and not has_behavior_lines:
            semantic_class = "structure"
            reason = "continuous region contains only structural statements"
        elif has_structure_lines and has_behavior_lines:
            semantic_class = "mixed"
            reason = "continuous region contains both structural and behavioral statements"
        else:
            semantic_class = "behavior"
            reason = "continuous region contains no structural statements"
        if semantic_class in {"structure", "mixed"}:
            structure_refs = _extract_structure_refs(code, chunk)
        return {
            "semantic_class": semantic_class,
            "guard_context": guard_context,
            "structure_refs": structure_refs,
            "compile_time_context": compile_time_context,
            "reason": reason,
        }

    has_behavior = bool(
        re.search(r"^\s*always(?:_(?:comb|ff|latch))?\b", code, flags=re.MULTILINE)
        or re.search(r"^\s*assign\b", code, flags=re.MULTILINE)
        or re.search(r"^\s*(?:function|task)\b", code, flags=re.MULTILINE)
    )
    has_structure = bool(
        re.search(r"^\s*(?:parameter|localparam)\b", code, flags=re.MULTILINE)
        or re.search(r"^\s*typedef\b", code, flags=re.MULTILINE)
        or re.search(r"^\s*(?:input|output|inout)\b", code, flags=re.MULTILINE)
        or _contains_instance_like(code)
    )

    if chunk.kind in {"always_comb", "always_ff", "always_latch", "function_task"}:
        semantic_class = "behavior"
        reason = f"procedural chunk kind={chunk.kind}"
    elif chunk.kind == "generate_for":
        semantic_class = "mixed"
        reason = "generate block may contain both structural and behavioral statements"
    elif has_structure and not has_behavior:
        semantic_class = "structure"
        reason = "contains declarations / instances / typedefs without procedural behavior"
    elif has_structure and has_behavior:
        semantic_class = "mixed"
        reason = "contains both declarative and behavioral statements"
    else:
        semantic_class = "behavior"
        reason = "default behavior chunk"

    if semantic_class in {"structure", "mixed"}:
        structure_refs = _extract_structure_refs(code, chunk)

    return {
        "semantic_class": semantic_class,
        "guard_context": guard_context,
        "structure_refs": structure_refs,
        "compile_time_context": compile_time_context,
        "reason": reason,
    }


def _split_continuous_region_for_structure(chunk: RtlChunk) -> list[RtlChunk]:
    """Split a continuous_region chunk into structure/behavior subchunks.

    This is intentionally conservative: only lines that are clearly structural
    (declarations, typedefs, parameters, or instance headers) are peeled into
    structural chunks. Everything else stays in behavioral chunks so that
    assign-heavy glue does not get mislabeled as structure.
    """
    lines = chunk.code.splitlines()
    groups: list[tuple[int, int, str]] = []

    current_role: str | None = None
    current_start: int | None = None
    inst_depth = 0
    typedef_depth = 0

    def flush(end_idx: int) -> None:
        nonlocal current_role, current_start
        if current_role is not None and current_start is not None and end_idx >= current_start:
            groups.append((current_start, end_idx, current_role))
        current_role = None
        current_start = None

    for idx, raw in enumerate(lines, start=chunk.line_start):
        stripped = _strip_line_comment(raw).strip()
        if not stripped or stripped.startswith("//"):
            continue

        in_inst_block = inst_depth > 0
        in_typedef_block = typedef_depth > 0
        role = _line_role(
            stripped,
            inst_depth=in_inst_block or _starts_instance_block(stripped),
            typedef_depth=in_typedef_block or _starts_typedef_block(stripped),
        )

        if current_role is None:
            current_role = role
            current_start = idx
        elif role != current_role:
            flush(idx - 1)
            current_role = role
            current_start = idx

        if _starts_instance_block(stripped):
            inst_depth = 1
        elif inst_depth > 0:
            inst_depth += stripped.count("(") - stripped.count(")")
            if stripped.endswith(");") or stripped == ");":
                inst_depth = 0

        if _starts_typedef_block(stripped):
            typedef_depth = 1
        elif typedef_depth > 0:
            typedef_depth += stripped.count("{") - stripped.count("}")
            if stripped.endswith(";") and "}" in stripped:
                typedef_depth = 0

    if current_role is not None and current_start is not None:
        flush(chunk.line_end)

    out: list[RtlChunk] = []
    counters: Counter[str] = Counter()
    for start, end, role in groups:
        sub_lines = lines[start - chunk.line_start : end - chunk.line_start + 1]
        if not _has_meaningful_code(sub_lines):
            continue
        sub_code = "\n".join(sub_lines)
        sub_kind = chunk.kind
        suffix = _safe_id(role)
        base = f"{_safe_id(chunk.chunk_id)}__{suffix}"
        counters[base] += 1
        out.append(
            RtlChunk(
                chunk_id=f"{base}__{counters[base]:03d}",
                kind=sub_kind,
                source_file=chunk.source_file,
                module=chunk.module,
                line_start=start,
                line_end=end,
                title=_title(sub_kind, f"{suffix}_{chunk.line_start}_{chunk.line_end}", chunk.module, start, end),
                context_summary=_context_summary(sub_kind, chunk.module, start, end),
                code=sub_code,
                dependencies=_extract_identifiers(sub_code),
            )
        )
    return out or [chunk]


def _starts_instance_block(line: str) -> bool:
    return bool(
        re.search(r"\b[A-Za-z_][A-Za-z0-9_$]*\s+#\(", line)
        or re.match(r"^\s*u_[A-Za-z_][A-Za-z0-9_$]*\s*(?:#\s*\(|\()", line)
        or re.search(r"\)\s*u_[A-Za-z_][A-Za-z0-9_$]*\s*\(", line)
    )


def _starts_typedef_block(line: str) -> bool:
    return bool(re.match(r"^\s*typedef\s+", line))


def _line_role(line: str, inst_depth: bool = False, typedef_depth: bool = False) -> str:
    stripped = line.strip()
    if not stripped or stripped.startswith("//"):
        return "neutral"
    if inst_depth or typedef_depth:
        return "structure"
    if re.match(r"^\s*(?:parameter|localparam)\b", line):
        return "structure"
    if re.match(r"^\s*typedef\b", line):
        return "structure"
    if re.match(r"^\s*(?:logic|bit|reg|wire|int|integer|byte|shortint|longint)\b", line):
        return "structure" if "=" not in line else "behavior"
    if _starts_instance_block(line):
        return "structure"
    if re.match(r"^\s*assign\b", line):
        return "behavior"
    if re.match(r"^\s*always(?:_(?:comb|ff|latch))?\b", line):
        return "behavior"
    if re.match(r"^\s*(?:function|task)\b", line):
        return "behavior"
    if re.match(r"^\s*(?:if|else|case|for|while)\b", line):
        return "behavior"
    return "behavior"


def _extract_compile_time_context(code: str) -> list[str]:
    items: list[str] = []
    for line in code.splitlines():
        stripped = _strip_line_comment(line).strip()
        if not stripped:
            continue
        m_if = re.match(r"^if\s*\((.+)\)\s*(?:begin\b|:)", stripped)
        if m_if:
            items.append(f"generate if: {m_if.group(1).strip()}")
            continue
        m_case = re.match(r"^case\s*\((.+)\)", stripped)
        if m_case:
            items.append(f"generate case: {m_case.group(1).strip()}")
            continue
        m_for = re.match(r"^for\s*\(\s*genvar\s+(.+)\)", stripped)
        if m_for:
            items.append(f"generate for: {m_for.group(1).strip()}")
            continue
    return list(dict.fromkeys(items))


def _contains_instance_like(code: str) -> bool:
    lines = code.splitlines()
    for idx, line in enumerate(lines):
        stripped = _strip_line_comment(line).strip()
        if not stripped or stripped.startswith("//"):
            continue
        if re.search(r"\b[A-Za-z_][A-Za-z0-9_$]*\s+#\(", stripped):
            return True
        if re.match(r"^[A-Za-z_][A-Za-z0-9_$]*\s+[A-Za-z_][A-Za-z0-9_$]*\s*(?:#\s*\(|\()", stripped):
            return True
        if stripped.startswith("u_") and "(" in stripped:
            return True
        if idx > 0 and re.match(r"^\s*\.([A-Za-z_][A-Za-z0-9_$]*)\s*\(", stripped):
            return True
    return False


def _extract_structure_refs(code: str, chunk: RtlChunk) -> list[str]:
    refs: list[str] = []
    for idx, line in enumerate(code.splitlines(), start=chunk.line_start):
        stripped = _strip_line_comment(line).strip()
        if not stripped:
            continue
        if re.match(r"^\s*(?:parameter|localparam)\b", stripped):
            refs.append(f"{chunk.source_file}:{idx}-param")
        elif re.match(r"^\s*typedef\s+enum\b", stripped):
            refs.append(f"{chunk.source_file}:{idx}-enum")
        elif re.match(r"^\s*typedef\s+struct\b", stripped):
            refs.append(f"{chunk.source_file}:{idx}-struct")
        elif re.search(r"\b[A-Za-z_][A-Za-z0-9_$]*\s+#\(", stripped) or stripped.startswith("u_"):
            refs.append(f"{chunk.source_file}:{idx}-instance")
    return list(dict.fromkeys(refs))


def _extract_structure_facts_from_chunk(chunk: RtlChunk) -> list[dict[str, object]]:
    facts: list[dict[str, object]] = []
    lines = chunk.code.splitlines()
    for offset, line in enumerate(lines, start=chunk.line_start):
        stripped = _strip_line_comment(line).strip()
        if not stripped:
            continue
        param_match = re.match(
            r"^\s*parameter\s+(?:logic\s+\[[^\]]+\]\s+|int(?:\s+unsigned)?\s+|bit\s+)?"
            r"([A-Za-z_][A-Za-z0-9_$]*)\s*=\s*(.+?);\s*$",
            stripped,
        )
        if param_match:
            facts.append(
                {
                    "fact_id": f"{chunk.chunk_id}__param_def__{offset}_{offset}__{param_match.group(1)}",
                    "kind": "param_def",
                    "name": param_match.group(1),
                    "source_file": chunk.source_file,
                    "line_start": offset,
                    "line_end": offset,
                    "expression": param_match.group(2).strip(),
                    "signals": [param_match.group(1)],
                    "tags": ["parameterization"],
                    "rank_score": 2,
                    "guard_context": chunk.guard_context,
                    "evidence_refs": [f"{Path(chunk.source_file).name}:{offset}-{offset}"],
                }
            )
            continue
        if re.match(r"^\s*typedef\s+enum\b", stripped):
            facts.append(
                {
                    "fact_id": f"{chunk.chunk_id}__enum_def__{offset}_{offset}__enum",
                    "kind": "enum_def",
                    "name": chunk.title,
                    "source_file": chunk.source_file,
                    "line_start": offset,
                    "line_end": offset,
                    "expression": stripped,
                    "signals": [],
                    "tags": ["enum", "typedef"],
                    "rank_score": 2,
                    "guard_context": chunk.guard_context,
                    "evidence_refs": [f"{Path(chunk.source_file).name}:{offset}-{offset}"],
                }
            )
            continue
        if re.match(r"^\s*typedef\s+struct\b", stripped):
            facts.append(
                {
                    "fact_id": f"{chunk.chunk_id}__struct_def__{offset}_{offset}__struct",
                    "kind": "struct_def",
                    "name": chunk.title,
                    "source_file": chunk.source_file,
                    "line_start": offset,
                    "line_end": offset,
                    "expression": stripped,
                    "signals": [],
                    "tags": ["struct", "typedef"],
                    "rank_score": 2,
                    "guard_context": chunk.guard_context,
                    "evidence_refs": [f"{Path(chunk.source_file).name}:{offset}-{offset}"],
                }
            )
            continue
        inst = _extract_instance_fact(chunk, stripped, offset)
        if inst is not None:
            facts.append(inst)
    return facts


def _extract_instance_fact(chunk: RtlChunk, stripped: str, line_no: int) -> dict[str, object] | None:
    if not (re.search(r"\b[A-Za-z_][A-Za-z0-9_$]*\s+#\(", stripped) or stripped.startswith("u_")):
        return None
    if "." not in stripped and "#(" not in stripped:
        return None
    inst_name = ""
    mod_name = ""
    header = stripped
    if "#(" in header:
        mod_name = header.split("#(", 1)[0].strip().split()[-1]
        inst_name = mod_name if mod_name.startswith("u_") else ""
    port_map: dict[str, str] = {}
    param_map: dict[str, str] = {}
    fact_id = f"{chunk.chunk_id}__instance_map__{line_no}_{line_no}__{_safe_id(inst_name or mod_name or 'inst')}"
    return {
        "fact_id": fact_id,
        "kind": "instance_map",
        "name": inst_name or mod_name,
        "module_name": mod_name,
        "instance_name": inst_name,
        "source_file": chunk.source_file,
        "line_start": line_no,
        "line_end": line_no,
        "expression": stripped,
        "signals": [],
        "tags": ["instance"],
        "rank_score": 2,
        "port_map": port_map,
        "param_map": param_map,
        "guard_context": chunk.guard_context,
        "evidence_refs": [f"{Path(chunk.source_file).name}:{line_no}-{line_no}"],
    }


def _collapse_run(run: list[RtlChunk]) -> RtlChunk:
    """Collapse a run of same-kind chunks into a single RtlChunk."""
    if len(run) == 1:
        return run[0]

    first, last = run[0], run[-1]
    combined_code = "\n".join(c.code for c in run)
    combined_deps = list(dict.fromkeys(
        dep for c in run for dep in (c.dependencies or [])
    ))[:40]

    merged = RtlChunk(
        chunk_id=first.chunk_id,  # keep the first chunk's id
        kind=first.kind,
        source_file=first.source_file,
        module=first.module,
        line_start=first.line_start,
        line_end=last.line_end,
        title=_title(
            first.kind,
            f"merged_{len(run)}_regions",
            first.module,
            first.line_start,
            last.line_end,
        ),
        context_summary=(
            f"合并的 {len(run)} 个相邻连续区域，"
            f"行 {first.line_start}-{last.line_end}。"
        ),
        code=combined_code,
        dependencies=combined_deps,
    )
    return merged
